name:                aeson-compact
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/aeson-compact#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2018 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - aeson-diff

library:
  source-dirs:      src

tests:
  test:
    source-dirs: test
    main: Spec.hs
    dependencies:
      - aeson-compact
      - hspec
      - QuickCheck
